package net.journey.dimension.senterian.room;

import java.util.Random;

import net.journey.dimension.senterian.SenterianChunkPrimer;
import net.journey.init.blocks.JourneyBlocks;
import net.minecraft.block.BlockColored;
import net.minecraft.block.state.IBlockState;
import net.minecraft.init.Blocks;
import net.minecraft.item.EnumDyeColor;

public class SenterianRoomMaze2 extends SenterianRoomBase {

	@Override
	public boolean generate(SenterianChunkPrimer worldIn, Random r, int i, int j, int k) {
		this.setBlock(worldIn, i, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 1, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 1, k + 1, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 1, k + 2, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 1, k + 3, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 1, k + 4, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 1, k + 5, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 1, k + 6, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 1, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i, j + 1, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i, j + 1, k + 9, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 1, k + 10, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 1, k + 11, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 1, k + 12, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 1, k + 13, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 1, k + 14, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 1, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 2, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 2, k + 1, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 2, k + 2, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 2, k + 3, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 2, k + 4, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 2, k + 5, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 2, k + 6, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 2, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i, j + 2, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i, j + 2, k + 9, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 2, k + 10, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 2, k + 11, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 2, k + 12, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 2, k + 13, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 2, k + 14, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 2, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 3, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 3, k + 1, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 3, k + 2, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 3, k + 3, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 3, k + 4, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 3, k + 5, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 3, k + 6, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 3, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i, j + 3, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i, j + 3, k + 9, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 3, k + 10, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 3, k + 11, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 3, k + 12, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 3, k + 13, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 3, k + 14, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 3, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 1, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 1, j + 1, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 1, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 1, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 1, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 1, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 1, j + 1, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 1, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 1, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 1, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 1, j + 1, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 1, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 1, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 1, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 1, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 1, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 1, j + 2, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 1, j + 2, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 2, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 2, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 2, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 2, k + 5, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 1, j + 2, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 2, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 2, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 2, k + 9, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 1, j + 2, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 2, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 2, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 2, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 2, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 2, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 1, j + 3, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 1, j + 3, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 3, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 3, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 3, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 3, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 1, j + 3, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 3, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 3, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 3, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 1, j + 3, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 3, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 3, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 3, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 3, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 1, j + 3, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 1, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 1, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 1, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 2, j + 1, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 1, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 1, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 1, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 1, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 1, k + 6, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 1, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 1, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 1, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 1, k + 10, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 1, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 1, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 1, k + 13, JourneyBlocks.journeyChest);
		this.setBlock(worldIn, i + 2, j + 1, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 1, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 2, j + 2, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 2, j + 2, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 2, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 2, k + 3, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 2, j + 2, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 2, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 2, k + 6, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 2, j + 2, k + 7, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 2, j + 2, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 2, k + 9, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 2, j + 2, k + 10, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 2, j + 2, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 2, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 2, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 2, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 2, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 2, j + 3, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 2, j + 3, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 3, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 3, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 3, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 3, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 3, k + 6, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 3, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 3, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 3, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 3, k + 10, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 3, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 3, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 2, j + 3, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 3, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 2, j + 3, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 2, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 2, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 1, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 3, j + 1, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 1, k + 2, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 3, j + 1, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 1, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 1, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 1, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 1, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 1, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 1, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 3, j + 1, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 1, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 1, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 3, j + 1, k + 13, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 3, j + 1, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 1, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 3, j + 2, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 3, j + 2, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 2, k + 2, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 3, j + 2, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 2, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 2, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 2, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 2, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 2, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 2, k + 9, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 3, j + 2, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 2, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 2, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 3, j + 2, k + 13, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 3, j + 2, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 2, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 3, j + 3, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 3, j + 3, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 3, k + 2, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 3, j + 3, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 3, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 3, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 3, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 3, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 3, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 3, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 3, j + 3, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 3, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 3, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 3, j + 3, k + 13, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 3, j + 3, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 3, j + 3, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 3, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 3, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 1, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 4, j + 1, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 1, k + 2, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 1, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 1, k + 4, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 1, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 1, k + 6, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 1, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 1, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 1, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 1, k + 10, Blocks.MOB_SPAWNER);
		this.setBlock(worldIn, i + 4, j + 1, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 1, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 1, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 1, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 1, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 4, j + 2, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 4, j + 2, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 2, k + 2, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 4, j + 2, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 2, k + 4, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 4, j + 2, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 2, k + 6, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 4, j + 2, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 2, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 2, k + 9, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 4, j + 2, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 2, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 2, k + 12, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 4, j + 2, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 2, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 2, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 4, j + 3, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 4, j + 3, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 3, k + 2, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 3, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 3, k + 4, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 3, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 3, k + 6, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 3, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 3, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 3, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 3, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 3, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 3, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 4, j + 3, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 3, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 4, j + 3, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 4, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 4, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 1, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 5, j + 1, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 1, k + 2, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 5, j + 1, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 1, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 1, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 5, j + 1, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 1, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 1, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 1, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 5, j + 1, k + 10, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 5, j + 1, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 1, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 5, j + 1, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 1, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 1, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 5, j + 2, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 5, j + 2, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 2, k + 2, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 5, j + 2, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 2, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 2, k + 5, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 5, j + 2, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 2, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 2, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 2, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 5, j + 2, k + 10, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 5, j + 2, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 2, k + 12, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 5, j + 2, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 2, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 2, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 5, j + 3, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 5, j + 3, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 3, k + 2, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 5, j + 3, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 3, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 3, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 5, j + 3, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 3, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 3, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 3, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 5, j + 3, k + 10, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 5, j + 3, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 3, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 5, j + 3, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 3, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 5, j + 3, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 5, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 5, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 1, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 6, j + 1, k + 1, JourneyBlocks.journeyChest);
		this.setBlock(worldIn, i + 6, j + 1, k + 2, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 1, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 1, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 1, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 1, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 1, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 1, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 1, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 1, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 1, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 1, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 1, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 1, k + 14, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 1, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 6, j + 2, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 6, j + 2, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 2, k + 2, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 2, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 2, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 2, k + 5, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 6, j + 2, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 2, k + 7, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 6, j + 2, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 2, k + 9, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 6, j + 2, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 2, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 2, k + 12, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 6, j + 2, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 2, k + 14, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 6, j + 2, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 6, j + 3, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 6, j + 3, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 3, k + 2, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 3, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 3, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 3, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 3, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 3, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 3, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 3, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 3, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 3, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 3, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 3, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 6, j + 3, k + 14, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 6, j + 3, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 6, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 6, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 1, k, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 1, k + 1, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 7, j + 1, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 1, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 1, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 1, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 7, j + 1, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 1, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 7, j + 1, k + 8, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 7, j + 1, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 7, j + 1, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 1, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 1, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 7, j + 1, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 1, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 1, k + 15, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 2, k, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 2, k + 1, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 7, j + 2, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 2, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 2, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 2, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 7, j + 2, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 2, k + 7, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 7, j + 2, k + 8, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 7, j + 2, k + 9, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 7, j + 2, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 2, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 2, k + 12, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 7, j + 2, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 2, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 2, k + 15, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 3, k, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 3, k + 1, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 7, j + 3, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 3, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 3, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 3, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 7, j + 3, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 3, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 7, j + 3, k + 8, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 7, j + 3, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 7, j + 3, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 3, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 3, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 7, j + 3, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 3, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 3, k + 15, Blocks.AIR);
		this.setBlock(worldIn, i + 7, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 7, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 1, k, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 1, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 1, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 1, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 8, j + 1, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 1, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 1, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 1, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 8, j + 1, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 1, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 1, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 1, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 1, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 1, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 1, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 1, k + 15, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 2, k, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 2, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 2, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 2, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 8, j + 2, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 2, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 2, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 2, k + 7, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 8, j + 2, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 2, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 2, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 2, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 2, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 2, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 2, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 2, k + 15, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 3, k, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 3, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 3, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 3, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 8, j + 3, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 3, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 3, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 3, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 8, j + 3, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 3, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 3, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 3, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 3, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 3, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 3, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 3, k + 15, Blocks.AIR);
		this.setBlock(worldIn, i + 8, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 8, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 1, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 9, j + 1, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 9, j + 1, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 9, j + 1, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 1, k + 4, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 1, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 9, j + 1, k + 6, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 1, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 1, k + 8, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 1, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 1, k + 10, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 1, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 9, j + 1, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 1, k + 13, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 1, k + 14, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 1, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 9, j + 2, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 9, j + 2, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 9, j + 2, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 9, j + 2, k + 3, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 9, j + 2, k + 4, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 2, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 9, j + 2, k + 6, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 2, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 2, k + 8, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 9, j + 2, k + 9, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 9, j + 2, k + 10, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 2, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 9, j + 2, k + 12, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 9, j + 2, k + 13, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 9, j + 2, k + 14, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 2, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 9, j + 3, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 9, j + 3, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 9, j + 3, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 9, j + 3, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 3, k + 4, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 3, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 9, j + 3, k + 6, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 3, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 3, k + 8, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 3, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 3, k + 10, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 3, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 9, j + 3, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 3, k + 13, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 3, k + 14, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 9, j + 3, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 9, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 9, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 1, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 10, j + 1, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 1, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 1, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 10, j + 1, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 1, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 1, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 1, k + 7, Blocks.MOB_SPAWNER);
		this.setBlock(worldIn, i + 10, j + 1, k + 8, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 10, j + 1, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 1, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 1, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 1, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 1, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 1, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 1, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 10, j + 2, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 10, j + 2, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 2, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 2, k + 3, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 10, j + 2, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 2, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 2, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 2, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 2, k + 8, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 10, j + 2, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 2, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 2, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 2, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 2, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 2, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 2, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 10, j + 3, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 10, j + 3, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 3, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 3, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 10, j + 3, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 3, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 3, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 3, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 3, k + 8, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 10, j + 3, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 3, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 3, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 3, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 3, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 3, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 10, j + 3, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 10, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 10, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 1, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 11, j + 1, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 1, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 1, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 11, j + 1, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 1, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 11, j + 1, k + 6, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 11, j + 1, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 11, j + 1, k + 8, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 11, j + 1, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 1, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 1, k + 11, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 11, j + 1, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 1, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 1, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 1, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 11, j + 2, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 11, j + 2, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 2, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 2, k + 3, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 11, j + 2, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 2, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 11, j + 2, k + 6, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 11, j + 2, k + 7, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 11, j + 2, k + 8, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 11, j + 2, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 2, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 2, k + 11, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 11, j + 2, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 2, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 2, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 2, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 11, j + 3, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 11, j + 3, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 3, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 3, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 11, j + 3, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 3, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 11, j + 3, k + 6, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 11, j + 3, k + 7, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 11, j + 3, k + 8, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 11, j + 3, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 3, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 3, k + 11, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 11, j + 3, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 3, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 3, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 11, j + 3, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 11, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 11, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 1, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 12, j + 1, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 1, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 1, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 12, j + 1, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 1, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 1, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 1, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 1, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 1, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 1, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 1, k + 11, JourneyBlocks.journeyChest);
		this.setBlock(worldIn, i + 12, j + 1, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 12, j + 1, k + 13, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 12, j + 1, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 1, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 12, j + 2, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 12, j + 2, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 2, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 2, k + 3, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 12, j + 2, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 2, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 2, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 2, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 2, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 2, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 2, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 2, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 2, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 12, j + 2, k + 13, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 12, j + 2, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 2, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 12, j + 3, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 12, j + 3, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 3, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 3, k + 3, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 12, j + 3, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 3, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 3, k + 6, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 3, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 3, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 3, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 3, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 3, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 3, k + 12, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 12, j + 3, k + 13, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 12, j + 3, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 12, j + 3, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 12, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 12, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 1, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 13, j + 1, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 1, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 1, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 1, k + 4, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 1, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 1, k + 6, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 1, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 1, k + 8, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 1, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 1, k + 10, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 1, k + 11, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 1, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 1, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 1, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 1, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 13, j + 2, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 13, j + 2, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 2, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 2, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 2, k + 4, JourneyBlocks.senterianMellowLamp);
		this.setBlock(worldIn, i + 13, j + 2, k + 5, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 13, j + 2, k + 6, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 13, j + 2, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 2, k + 8, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 2, k + 9, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 13, j + 2, k + 10, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 13, j + 2, k + 11, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 2, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 2, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 2, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 2, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 13, j + 3, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 13, j + 3, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 3, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 3, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 3, k + 4, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 3, k + 5, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 3, k + 6, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 3, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 3, k + 8, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 3, k + 9, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 3, k + 10, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 3, k + 11, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 13, j + 3, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 3, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 3, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 13, j + 3, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 13, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 13, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 1, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 14, j + 1, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 1, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 1, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 1, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 1, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 1, k + 6, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 14, j + 1, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 1, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 1, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 1, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 1, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 1, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 1, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 1, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 1, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 14, j + 2, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 14, j + 2, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 2, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 2, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 2, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 2, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 2, k + 6, JourneyBlocks.senterianBars);
		this.setBlock(worldIn, i + 14, j + 2, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 2, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 2, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 2, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 2, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 2, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 2, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 2, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 2, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 14, j + 3, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 14, j + 3, k + 1, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 3, k + 2, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 3, k + 3, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 3, k + 4, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 3, k + 5, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 3, k + 6, JourneyBlocks.senterianBricks);
		this.setBlock(worldIn, i + 14, j + 3, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 3, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 3, k + 9, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 3, k + 10, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 3, k + 11, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 3, k + 12, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 3, k + 13, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 3, k + 14, Blocks.AIR);
		this.setBlock(worldIn, i + 14, j + 3, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 14, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 14, j + 4, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j, k + 15, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 1, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 1, k + 1, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 1, k + 2, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 1, k + 3, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 1, k + 4, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 1, k + 5, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 1, k + 6, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 1, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 15, j + 1, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 15, j + 1, k + 9, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 1, k + 10, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 1, k + 11, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 1, k + 12, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 1, k + 13, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 1, k + 14, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 1, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 2, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 2, k + 1, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 2, k + 2, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 2, k + 3, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 2, k + 4, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 2, k + 5, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 2, k + 6, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 2, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 15, j + 2, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 15, j + 2, k + 9, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 2, k + 10, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 2, k + 11, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 2, k + 12, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 2, k + 13, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 2, k + 14, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 2, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 3, k, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 3, k + 1, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 3, k + 2, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 3, k + 3, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 3, k + 4, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 3, k + 5, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 3, k + 6, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 3, k + 7, Blocks.AIR);
		this.setBlock(worldIn, i + 15, j + 3, k + 8, Blocks.AIR);
		this.setBlock(worldIn, i + 15, j + 3, k + 9, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 3, k + 10, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 3, k + 11, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 3, k + 12, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 3, k + 13, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 3, k + 14, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 3, k + 15, JourneyBlocks.senterianCarvedRock);
		this.setBlock(worldIn, i + 15, j + 4, k, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 1, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 2, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 3, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 4, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 5, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 6, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 7, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 8, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 9, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 10, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 11, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 12, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 13, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 14, JourneyBlocks.senterianFloor);
		this.setBlock(worldIn, i + 15, j + 4, k + 15, JourneyBlocks.senterianFloor);
		return true;
	}
}