package net.journey;

import net.journey.proxy.CommonProxy;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.slayer.api.SlayerAPI;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.util.ArrayList;

@Mod(name = JITL.MOD_NAME, modid = JITL.MOD_ID, version = JITL.MOD_VERSION)
public class JITL {
	public static final String MOD_NAME = "Journey Into the Light";
	public static final String MOD_ID = "journey";
	public static final String MOD_VERSION = "GRADLETOKEN_VERSION"; //will be automatically changed during build task

	/**
	 * Equals true only if journey is launched in its development workspace.
	 * Will be set to false in any other mod dev workspace.
	 */
	public static final boolean IN_JOURNEY_DEV = true; // will be automatically replaced to false during build
	public static final Logger LOGGER = LogManager.getLogger(MOD_NAME);

	@Instance(JITL.MOD_ID)
	public static JITL instance;
	@SidedProxy(clientSide = "net.journey.proxy.ClientProxy", serverSide = "net.journey.proxy.CommonProxy")
	public static CommonProxy proxy;

	@EventHandler
	public static void preInit(FMLPreInitializationEvent event) {
		proxy.preInit(event);
		proxy.registerClient();
		proxy.clientPreInit();
		ArrayList<String> author = new ArrayList<>();
		author.add("The_SlayerMC");
		event.getModMetadata().autogenerated = false;
		event.getModMetadata().credits =
				SlayerAPI.Colour.AQUA + "The_SlayerMC - Owner/Creator/Developer/Code/Assets/Music, " +
						SlayerAPI.Colour.GREEN + "Dash - Code Helper/Gen Tweaker, " +
						SlayerAPI.Colour.BLUE + "Dizzlepop12 - Artist/Music/Models/Code/Co-Developer, " +
						SlayerAPI.Colour.LIGHT_PURPLE + "TimeConqueror - Code Helper, Co-Developer, " +
						SlayerAPI.Colour.DARK_AQUA + "NicosaurusRex99 - Code ";
		event.getModMetadata().description = "A full progressional experience that adds Weapons, Mobs, Dimensions, Bosses, and much more to your game.";
		event.getModMetadata().modId = JITL.MOD_ID;
		event.getModMetadata().url = "https://slayermods.net";
		event.getModMetadata().name = JITL.MOD_NAME;
		event.getModMetadata().version = JITL.MOD_VERSION;
		event.getModMetadata().logoFile = "assets/journey/textures/logo.png";
		event.getModMetadata().authorList = author;
	}

	@EventHandler
	public static void init(FMLInitializationEvent event) {
		proxy.init(event);
		proxy.clientInit(event);
	}

	@EventHandler
	public static void postInit(FMLPostInitializationEvent event) {
		proxy.postInit(event);
		proxy.registerSounds();
		proxy.clientPostInit();
	}

	@EventHandler
	public static void serverStarting(FMLServerStartingEvent event) {
		SlayerAPI.logger.info("Starting server...");
		proxy.serverStarting(event);
	}
}
