package net.journey.client.render.model.mob.boss;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelEnderChampion extends ModelBase {

    ModelRenderer Chest;
    ModelRenderer Back;
    ModelRenderer Rib1;
    ModelRenderer Rib2;
    ModelRenderer Rib3;
    ModelRenderer Rib4;
    ModelRenderer Rib5;
    ModelRenderer Rib6;
    ModelRenderer Rib7;
    ModelRenderer SomeBone;
    ModelRenderer LeftUpperLegBone;
    ModelRenderer RightUpperLegBone;
    ModelRenderer LeftBackwardKnee;
    ModelRenderer RightBackwardKnee;
    ModelRenderer LeftFoot;
    ModelRenderer RightFoot;
    ModelRenderer LeftLegSpike;
    ModelRenderer RightLegSpike;
    ModelRenderer RightShoulder;
    ModelRenderer LeftShoulder;
    ModelRenderer RightElbow;
    ModelRenderer LeftElbow;
    ModelRenderer LeftArm;
    ModelRenderer RightArm;
    ModelRenderer RightArmSpike;
    ModelRenderer LeftArmSpike;
    ModelRenderer Head;
    ModelRenderer RightShoulderSpikeBase;
    ModelRenderer LeftShoulderSpikeBase;
    ModelRenderer RightSpikeEnd;
    ModelRenderer LeftSpikeEnd;
    ModelRenderer RightShield;
    ModelRenderer LeftShield;

    public ModelEnderChampion() {
        textureWidth = 128;
        textureHeight = 64;

        Chest = new ModelRenderer(this, 0, 0);
        Chest.addBox(-7.5F, 0F, -4.5F, 15, 7, 9);
        Chest.setRotationPoint(0F, -12F, 0F);
        Chest.setTextureSize(128, 64);
        Chest.mirror = true;
        setRotation(Chest, 0F, 0F, 0F);
        Back = new ModelRenderer(this, 0, 16);
        Back.addBox(-1F, 0F, -1F, 2, 12, 2);
        Back.setRotationPoint(0F, -5F, 0F);
        Back.setTextureSize(128, 64);
        Back.mirror = true;
        setRotation(Back, 0F, 0F, 0F);
        Rib1 = new ModelRenderer(this, 8, 16);
        Rib1.addBox(-2F, -0.5F, -0.5F, 4, 1, 1);
        Rib1.setRotationPoint(0F, -4F, 0F);
        Rib1.setTextureSize(128, 64);
        Rib1.mirror = true;
        setRotation(Rib1, 0F, 0F, 0F);
        Rib2 = new ModelRenderer(this, 8, 18);
        Rib2.addBox(-3F, -0.5F, -0.5F, 6, 1, 1);
        Rib2.setRotationPoint(0F, -2.5F, 0F);
        Rib2.setTextureSize(128, 64);
        Rib2.mirror = true;
        setRotation(Rib2, 0F, 0F, 0F);
        Rib3 = new ModelRenderer(this, 8, 20);
        Rib3.addBox(-4F, -0.5F, -0.5F, 8, 1, 1);
        Rib3.setRotationPoint(0F, -1F, 0F);
        Rib3.setTextureSize(128, 64);
        Rib3.mirror = true;
        setRotation(Rib3, 0F, 0F, 0F);
        Rib4 = new ModelRenderer(this, 8, 22);
        Rib4.addBox(-5F, -0.5F, -0.5F, 10, 1, 1);
        Rib4.setRotationPoint(0F, 0.5F, 0F);
        Rib4.setTextureSize(128, 64);
        Rib4.mirror = true;
        setRotation(Rib4, 0F, 0F, 0F);
        Rib5 = new ModelRenderer(this, 8, 20);
        Rib5.addBox(-4F, -0.5F, -0.5F, 8, 1, 1);
        Rib5.setRotationPoint(0F, 2F, 0F);
        Rib5.setTextureSize(128, 64);
        Rib5.mirror = true;
        setRotation(Rib5, 0F, 0F, 0F);
        Rib6 = new ModelRenderer(this, 8, 18);
        Rib6.addBox(-3F, -0.5F, -0.5F, 6, 1, 1);
        Rib6.setRotationPoint(0F, 3.5F, 0F);
        Rib6.setTextureSize(128, 64);
        Rib6.mirror = true;
        setRotation(Rib6, 0F, 0F, 0F);
        Rib7 = new ModelRenderer(this, 8, 16);
        Rib7.addBox(-2F, -0.5F, -0.5F, 4, 1, 1);
        Rib7.setRotationPoint(0F, 5F, 0F);
        Rib7.setTextureSize(128, 64);
        Rib7.mirror = true;
        setRotation(Rib7, 0F, 0F, 0F);
        SomeBone = new ModelRenderer(this, 8, 24);
        SomeBone.addBox(-5F, 0F, -1.5F, 10, 3, 3);
        SomeBone.setRotationPoint(0F, 7F, 0F);
        SomeBone.setTextureSize(128, 64);
        SomeBone.mirror = true;
        setRotation(SomeBone, 0F, 0F, 0F);
        LeftUpperLegBone = new ModelRenderer(this, 0, 30);
        LeftUpperLegBone.addBox(-1F, -1F, -1F, 2, 8, 2);
        LeftUpperLegBone.setRotationPoint(4F, 9F, 0F);
        LeftUpperLegBone.setTextureSize(128, 64);
        LeftUpperLegBone.mirror = true;
        setRotation(LeftUpperLegBone, 0.4537856F, 0F, 0F);
        RightUpperLegBone = new ModelRenderer(this, 0, 30);
        RightUpperLegBone.addBox(-1F, -1F, -1F, 2, 8, 2);
        RightUpperLegBone.setRotationPoint(-4F, 9F, 0F);
        RightUpperLegBone.setTextureSize(128, 64);
        RightUpperLegBone.mirror = true;
        setRotation(RightUpperLegBone, 0.4537856F, 0F, 0F);
        LeftBackwardKnee = new ModelRenderer(this, 0, 40);
        LeftBackwardKnee.addBox(-1F, -1F, 0.5F, 2, 9, 2);
        LeftBackwardKnee.setRotationPoint(4F, 14F, 2F);
        LeftBackwardKnee.setTextureSize(128, 64);
        LeftBackwardKnee.mirror = true;
        setRotation(LeftBackwardKnee, -0.3141593F, 0F, 0F);
        RightBackwardKnee = new ModelRenderer(this, 0, 40);
        RightBackwardKnee.addBox(-1F, -1F, 0.5F, 2, 9, 2);
        RightBackwardKnee.setRotationPoint(-4F, 14F, 2F);
        RightBackwardKnee.setTextureSize(128, 64);
        RightBackwardKnee.mirror = true;
        setRotation(RightBackwardKnee, -0.3141593F, 0F, 0F);
        LeftFoot = new ModelRenderer(this, 8, 30);
        LeftFoot.addBox(-1F, 0F, -4F, 2, 2, 5);
        LeftFoot.setRotationPoint(4F, 22F, 1F);
        LeftFoot.setTextureSize(128, 64);
        LeftFoot.mirror = true;
        setRotation(LeftFoot, 0F, 0F, 0F);
        RightFoot = new ModelRenderer(this, 8, 30);
        RightFoot.addBox(-1F, 0F, -4F, 2, 2, 5);
        RightFoot.setRotationPoint(-4F, 22F, 1F);
        RightFoot.setTextureSize(128, 64);
        RightFoot.mirror = true;
        setRotation(RightFoot, 0F, 0F, 0F);
        LeftLegSpike = new ModelRenderer(this, 8, 37);
        LeftLegSpike.addBox(-0.5F, -4F, -0.5F, 1, 5, 1);
        LeftLegSpike.setRotationPoint(4F, 14F, 4F);
        LeftLegSpike.setTextureSize(128, 64);
        LeftLegSpike.mirror = true;
        setRotation(LeftLegSpike, -0.2792527F, 0F, 0F);
        RightLegSpike = new ModelRenderer(this, 8, 37);
        RightLegSpike.addBox(-0.5F, -4F, -0.5F, 1, 5, 1);
        RightLegSpike.setRotationPoint(-4F, 14F, 4F);
        RightLegSpike.setTextureSize(128, 64);
        RightLegSpike.mirror = true;
        setRotation(RightLegSpike, -0.2792527F, 0F, 0F);
        RightShoulder = new ModelRenderer(this, 48, 0);
        RightShoulder.addBox(-8F, -4F, -4F, 8, 8, 8);
        RightShoulder.setRotationPoint(-7.5F, -9F, 0F);
        RightShoulder.setTextureSize(128, 64);
        RightShoulder.mirror = true;
        setRotation(RightShoulder, 0F, 0F, 0F);
        LeftShoulder = new ModelRenderer(this, 48, 0);
        LeftShoulder.addBox(0F, -4F, -4F, 8, 8, 8);
        LeftShoulder.setRotationPoint(7.5F, -9F, 0F);
        LeftShoulder.setTextureSize(128, 64);
        LeftShoulder.mirror = true;
        setRotation(LeftShoulder, 0F, 0F, 0F);
        RightElbow = new ModelRenderer(this, 0, 51);
        RightElbow.addBox(-1F, 0F, -1F, 2, 9, 2);
        RightElbow.setRotationPoint(-12F, -6F, 0F);
        RightElbow.setTextureSize(128, 64);
        RightElbow.mirror = true;
        setRotation(RightElbow, 0.5235988F, 0F, 0F);
        LeftElbow = new ModelRenderer(this, 0, 51);
        LeftElbow.addBox(-1F, 0F, -1F, 2, 9, 2);
        LeftElbow.setRotationPoint(12F, -6F, 0F);
        LeftElbow.setTextureSize(128, 64);
        LeftElbow.mirror = true;
        setRotation(LeftElbow, 0.5235988F, 0F, 0F);
        LeftArm = new ModelRenderer(this, 8, 43);
        LeftArm.addBox(-1F, -1F, -1F, 2, 14, 2);
        LeftArm.setRotationPoint(12F, 1F, 5F);
        LeftArm.setTextureSize(128, 64);
        LeftArm.mirror = true;
        setRotation(LeftArm, -0.6632251F, 0F, 0F);
        RightArm = new ModelRenderer(this, 8, 43);
        RightArm.addBox(-1F, -1F, -1F, 2, 14, 2);
        RightArm.setRotationPoint(-12F, 1F, 5F);
        RightArm.setTextureSize(128, 64);
        RightArm.mirror = true;
        setRotation(RightArm, -0.6632251F, 0F, 0F);
        RightArmSpike = new ModelRenderer(this, 16, 43);
        RightArmSpike.addBox(0F, 0F, -1F, 1, 7, 1);
        RightArmSpike.setRotationPoint(-12F, 1F, 5F);
        RightArmSpike.setTextureSize(128, 64);
        RightArmSpike.mirror = true;
        setRotation(RightArmSpike, 2.844887F, 0F, 0F);
        LeftArmSpike = new ModelRenderer(this, 16, 43);
        LeftArmSpike.addBox(0F, 0F, -1F, 1, 7, 1);
        LeftArmSpike.setRotationPoint(12F, 1F, 5F);
        LeftArmSpike.setTextureSize(128, 64);
        LeftArmSpike.mirror = true;
        setRotation(LeftArmSpike, 2.844887F, 0F, 0F);
        Head = new ModelRenderer(this, 80, 0);
        Head.addBox(-3F, -6F, -3F, 6, 6, 6);
        Head.setRotationPoint(0F, -12F, 0F);
        Head.setTextureSize(128, 64);
        Head.mirror = true;
        setRotation(Head, 0F, 0F, 0F);
        RightShoulderSpikeBase = new ModelRenderer(this, 34, 16);
        RightShoulderSpikeBase.addBox(-1F, -6F, -1F, 2, 7, 2);
        RightShoulderSpikeBase.setRotationPoint(-12F, -13F, 0F);
        RightShoulderSpikeBase.setTextureSize(128, 64);
        RightShoulderSpikeBase.mirror = true;
        setRotation(RightShoulderSpikeBase, 0F, 0F, -0.3490659F);
        LeftShoulderSpikeBase = new ModelRenderer(this, 34, 16);
        LeftShoulderSpikeBase.addBox(-1F, -6F, -1F, 2, 7, 2);
        LeftShoulderSpikeBase.setRotationPoint(12F, -13F, 0F);
        LeftShoulderSpikeBase.setTextureSize(128, 64);
        LeftShoulderSpikeBase.mirror = true;
        setRotation(LeftShoulderSpikeBase, 0F, 0F, 0.3490659F);
        RightSpikeEnd = new ModelRenderer(this, 42, 16);
        RightSpikeEnd.addBox(-0.5F, -7F, -0.5F, 1, 7, 1);
        RightSpikeEnd.setRotationPoint(-14F, -18F, 0F);
        RightSpikeEnd.setTextureSize(128, 64);
        RightSpikeEnd.mirror = true;
        setRotation(RightSpikeEnd, 0F, 0F, 0.6632251F);
        LeftSpikeEnd = new ModelRenderer(this, 42, 16);
        LeftSpikeEnd.addBox(-0.5F, -7F, -0.5F, 1, 7, 1);
        LeftSpikeEnd.setRotationPoint(14F, -18F, 0F);
        LeftSpikeEnd.setTextureSize(128, 64);
        LeftSpikeEnd.mirror = true;
        setRotation(LeftSpikeEnd, 0F, 0F, -0.6632251F);
        RightShield = new ModelRenderer(this, 104, 0);
        RightShield.addBox(-1F, -4.5F, -4.5F, 1, 9, 9);
        RightShield.setRotationPoint(-13F, 7F, 0F);
        RightShield.setTextureSize(128, 64);
        RightShield.mirror = true;
        setRotation(RightShield, -0.6632251F, 0F, 0F);
        LeftShield = new ModelRenderer(this, 104, 0);
        LeftShield.addBox(0F, -4.5F, -4.5F, 1, 9, 9);
        LeftShield.setRotationPoint(13F, 7F, 0F);
        LeftShield.setTextureSize(128, 64);
        LeftShield.mirror = true;
        setRotation(LeftShield, -0.6632251F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Chest.render(f5);
        Back.render(f5);
        Rib1.render(f5);
        Rib2.render(f5);
        Rib3.render(f5);
        Rib4.render(f5);
        Rib5.render(f5);
        Rib6.render(f5);
        Rib7.render(f5);
        SomeBone.render(f5);
        LeftUpperLegBone.render(f5);
        RightUpperLegBone.render(f5);
        LeftBackwardKnee.render(f5);
        RightBackwardKnee.render(f5);
        LeftFoot.render(f5);
        RightFoot.render(f5);
        LeftLegSpike.render(f5);
        RightLegSpike.render(f5);
        RightShoulder.render(f5);
        LeftShoulder.render(f5);
        RightElbow.render(f5);
        LeftElbow.render(f5);
        LeftArm.render(f5);
        RightArm.render(f5);
        RightArmSpike.render(f5);
        LeftArmSpike.render(f5);
        Head.render(f5);
        RightShoulderSpikeBase.render(f5);
        LeftShoulderSpikeBase.render(f5);
        RightSpikeEnd.render(f5);
        LeftSpikeEnd.render(f5);
        RightShield.render(f5);
        LeftShield.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
    }
}